name: Playwright Automation Tests

on:
  push:
    branches:
      - main

jobs:
  playwright-tests:

    runs-on: ubuntu-latest

    env:
      STANDARD_USER: standard_user
      PASSWORD: secret_sauce
      INVALID_USER: invalid_user
      INVALID_PASSWORD: invalid

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        run: npm install

      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      - name: Run automation tests
        run: npx cucumber-js

      - name: Upload test reports
        uses: actions/upload-artifact@v4
        with:
          name: test-report
          path: reports/